name = "samsara-saga"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-08-10"

[assets]
directory = ".svelte-kit/cloudflare/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB" # This MUST match the variable name used in the Dashboard
database_name = "samsara-saga-db"
database_id = "6867de4b-269e-4c9d-8658-b5632a0aa8de"
migrations_dir = "db/migrations"

[vars]
ENVIRONMENT = "development"
GEMINI_API_KEY = "AIzaSyDh5pwx9pvgP5vV6i6LvL78RuUaegcbD1U" # <--- REPLACE THIS WITH YOUR ACTUAL KEY

[[ai]]
binding = "AI" # This is the binding name you'll use in your WorkerGET method not allowed