name = "samsara-saga"
main = "./.svelte-kit/cloudflare/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./.svelte-kit/cloudflare"
entry-point = "./.svelte-kit/cloudflare"

[build]
command = "npm run build"
dir = "./.svelte-kit/cloudflare"
