PRAGMA foreign_keys = OFF;
PRAGMA defer_foreign_keys = ON;

DROP TABLE IF EXISTS Players;
DROP TABLE IF EXISTS PlayerState;
DROP TABLE IF EXISTS PlayerInventory;
DROP TABLE IF EXISTS NPC_Conversations;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Recipes;
DROP TABLE IF EXISTS LocationConnections;
DROP TABLE IF EXISTS NPCs;
DROP TABLE IF EXISTS Quests;
DROP TABLE IF EXISTS LocationItems;
DROP TABLE IF EXISTS Companions;
DROP TABLE IF EXISTS PlayerCompanions;